[index]
embedding_model = "BGESmallENV15Q"   
persist_path    = "../target/.ddr-index"             
chunk_size      = 512                         
chunk_overlap   = 64

[server]
log_level = "debug"    # debug | info | warn | error
