[file]
file_size_limit_mb = 2
glob_patterns = ["*.md"]

[git]
branch = "main"
depth_limit = 2
glob_patterns = ["*.rs", "*.java", "*.py", "*.js", "*.ts", "*.go"]

[index]
chunk_overlap = 64
chunk_size = 512
embedding_model = "BGESmallENV15Q"
max_size_mb = 4
persist_path = "./e2e-tests/.ddr-index"

[search]
same_src_score_decay = 0.9

[server]
log_level = "debug"
port = 7878
