#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-${(%):-%x}}")" &> /dev/null && pwd)


if [[ ":$PATH:" != *":$SCRIPT_DIR/target/debug:"* ]]; then
	export PATH="$SCRIPT_DIR/target/debug:$PATH"
	echo "$SCRIPT_DIR/target/debug added to PATH"
else
	echo "$SCRIPT_DIR/target/debug already in PATH"
fi

# Check if 'which python' returns a path inside .venv; if so, skip venv setup
PYTHON_PATH=$(which python)
if [[ "$PYTHON_PATH" == "$SCRIPT_DIR/.venv"* ]]; then
	echo "Python in .venv already active: $PYTHON_PATH"
else
	python3 -m venv "$SCRIPT_DIR/.venv"
	source "$SCRIPT_DIR/.venv/bin/activate"
	echo "Python virtual environment activated."
	echo "---"
fi

# Check if ./target is mounted as tmpfs
if ! mount | grep -q "on $SCRIPT_DIR/target type tmpfs"; then
	echo "[Warning] ./target is not mounted as tmpfs. Run ./mount_tmpfs.sh to mount it for best performance."
fi

export DOCENT_ADDR=127.0.0.1:7878
echo "DOCENT_ADDR=$DOCENT_ADDR"
